python my_main_source.py seg_nih_formae128 \
    -G $1 \
    --method seg_train \
    --train_list NIH_train \
    --val_list NIH_val \
    --data_root /data/MING/data/NIH \
    --val_data_root /data/MING/data/NIH \
    --data_path /data/MING/code/VAE_06/data/My_Multi_all.json \
    --eval_epoch 20 \
    --save_epoch 800 \
    --max_epoch 2400 \
    --batch_size 1 \
    --load_prefix seg_nih_formae128 \
